version: 2.1

jobs:
  deploy-to-aws:
    docker:
      - image: cimg/node:lts
    resource_class: small

    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm package cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            corepack prepare pnpm@latest --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install dependencies
          command: pnpm install
      - run:
          name: Deploy with SST
          command: pnpm deploy:frontend
      - save_cache:
          name: Save pnpm package cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store

workflows:
  deploy:
    jobs:
      - deploy-to-aws
