version: 2.1

jobs:
  deploy-to-aws:
    docker:
      - image: cimg/node:lts
    resource_class: small

    steps:
      - checkout
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            corepack prepare pnpm@latest --activate
      - run:
          name: Install dependencies
          command: |
            cd frontend
            pnpm install
      - run:
          name: Deploy with SST
          command: pnpm deploy

workflows:
  deploy:
    jobs:
      - deploy-to-aws
