# fly.toml app configuration file generated for marker-blog-cms on 2024-02-19T21:56:22+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'marker-blog-cms'
primary_region = 'waw'

[build]
dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
